services:
  stats-db:
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "6541:5432"

  stats-server:
    build: ./ewm-stats-server
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
    ports:
      - "9090:9090"

  ewm-db:
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
    ports:
      - "6542:5432"

  ewm-service:
    build: ./ewm-main-service
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
